# Generated by Django 2.2 on 2020-05-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200519_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=25, unique=True),
            preserve_default=False,
        ),
    ]
